version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=secret-key
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - app-db:/usr/src/app/db
    restart: unless-stopped

volumes:
  app-db: